<div class='container-bg'>
	<ul class='container'>
		<li class='drop-to-sort' parent-id='0'></li>
	</ul>
</div>
<div><a herf='javascript:void(0)' class='create-link'>添加新链接</a></div>

<script>
saveSort = function() {
	var prompt = Prompt.getInstance().showLoadingBox();
	prompt.hideHintBox();
	
	var treeleafs = $('.treeleaf-item');
	var sortJsonStr = '{';
	treeleafs.each(function(i, leaf) {
		sortJsonStr += '"' + $(leaf).attr('id') +'":{"parentId":"'+$(leaf).attr('parent-id')+'", "sort":' + i + '},';
	});
	sortJsonStr = sortJsonStr.substring(0, sortJsonStr.length - 1);
	sortJsonStr += '}';
	
	$.ajax({
		url: '/admin/navi/tree-sort/',
		data: {treeId: "<?php echo $this->naviDoc->getId()?>", sortJsonStr: sortJsonStr},
		type: 'post',
		success: function(json) {
			prompt.hideLoadingBox();
			$('.changed').removeClass('changed');
		}
	});	
};

//global defines
var tree = {type: 'navi', id: '<?php echo $this->naviDoc->getId()?>'};
</script>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/treeleaf" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>

<script type='text/template' id='treeleaf-item-template'>
	<% if(parentId == '') {%>
	<div class='leaf-line changed'>
	<% } else { %>
	<div class='leaf-line'>
	<% } %>
		<div class='drag-handle' draggable='true'></div>
		<div class='leaf-label'><a href='javascript:void(0)' class='edit' id='{{ id }}'>{{ label }}</a></div>
		<div class='leaf-link'>{{ link }}</div>
		<div class='clear'></div>
	</div>
	<ul class='children'>
		<li class='drop-to-sort' parent-id='{{ id }}'></li>
	</ul>
</script>
<script type='text/template' id='treeleaf-editor'>
	<div class='editor-title'>新建/修改链接</div>
	<div class='editor-contenr'>
		<div class='label-el'>链接名：</div>
		<div><input class='edit-value' name='label' type='text' value='{{ label }}'></div>
		<div class='link-el'>链接地址：</div>
		<div><input class='edit-value' name='link' type='text' value='{{ link }}'></div>
		<div class='css-el'>CSS Name：</div>
		<div><input class='edit-value' name='css' type='text' value='{{ css }}'></div>
		<a class='edit-save button' href='javascript:void(0)'>保存</a>
		<a class='edit-delete button' href='javascript:void(0)'>删除</a>
	</div>
</script>

<script>
var showEditor = function(){
	var model = new Treeleaf();
	var tlEditor = new TreeleafEditorView({
		model:model
	});
	tlEditor.render();
}
$('.create-link').click(function(){
	showEditor();
});
</script>
