<ul id='address-selector-list'>
<?php foreach($this->addressList as $address) { ?>
	<li>
		<input id='address_<?php echo $address['id']?>' type='radio' name='address' value='<?php echo $address['id']?>' />
		<label for='address_<?php echo $address['id']?>'><?php echo $address['fullAddress'] ?></label>
	</li>
<?php } ?>
</ul>

<form method='post' action='' id='address-selector-newform'></form>

<input id='address-selector-newbutton' type='button' name='' value='' />

<script type='text/javascript'>

</script>