<?php
	foreach($this->rowset as $row) {
	echo "<a class='brick-selector-row link' href='/admin/brick/edit/extName/$row->name/layoutId/$this->layoutId/stageId/$this->stageId/spriteName/$this->spriteName/'>";
?>
		<div class='icon extension-icon <?php echo $row->name ?>'></div>
		<div class='detail'>
			<div class='ext-name'><?php echo $row->name ?></div>
			<?php echo $row->label?><br /><br />
			<?php echo $row->desc?>
		</div>
<?php
	echo "</a>";
	}
?>