<?=$this->form?>
<div class='clear'></div>

<script type='text/javascript'>
//var lightBox = FINDER;
//
//var getImagePath = function(path) {
//	return path;
//}
//
//$('.file').live('click', function(e) {
//	getImagePath($(this).attr('path'));
//	FINDER.hide();
//});
//
//var imageSelector = $(".icon-selector");
//imageSelector.css({'background-color':'#ddeeff'});
//imageSelector.click(function() {
//	FINDER.show();
//	if(FINDER.attr('currentGroup') != 'icon') {
//		$.ajax({
//			url: "/admin/file/list/layout/disable",
//			success: function(HTML) {
//				content = FINDER.appendToContent(HTML);
//				getImagePath = function(path) {	
//					imageSelector.val(path);
//				}
//			}
//		});
//	}
//});
</script>