<div class='find-pwd'>
<form method="POST" action="<?=$this->url(array('module'=>'default','controller'=>'user','action'=>'forgot-password'),'default',true) ?>">
    <div class='pwd'>
        <div class='label'>
            邮箱地址：
        <div>
        <input class='email' type="text" name="email" id="email" value=""  />
        <div class='message'><?if(!empty($this->result)) echo '<span style="color:red;">'.$this->result.'</span>'; else echo '密码将发送到您注册的邮箱'; ?></div>
        <input class='sub' type="submit" value=""/>
    </div>
</form>
</div>