<div class='login'>
	<div class='title'><?php echo $this->translate('user login')?></div>
	<div class='content'>
		<?php echo $this->loginForm ?>
		<div class='forgot-password'>
			<a href="<?=$this->url(array('module'=>'user','controller'=>'index','action'=>'forgot-password'),'default',true) ?>"><?php echo $this->translate('forget password')?></a>
		</div>
		<div class='register-new'>
			<a href="<?=$this->url(array('module'=>'user','controller'=>'index','action'=>'register'),'default',true) ?>"><?php echo $this->translate('sign up')?></a>
		</div>
	</div>
</div>