<div class='register'>
	<div class='title'>新用户注册</div>
	<div class='content'>
		<?php echo $this->registerForm ?>
		<div class='forgot-password'>
			<a href="<?=$this->url(array('module'=>'user','controller'=>'index','action'=>'forgot-password'),'default',true) ?>">忘记密码</a>
		</div>
		<div class='register-new'>
			<a href="<?=$this->url(array('module'=>'user','controller'=>'index','action'=>'login'),'default',true) ?>">用户登陆</a>
		</div>
	</div>
</div>
