<?php
//build layout selector
$tb = Class_Base::_('Layout');
$rowset = $tb->fetchAll();
$defaultLayoutArr = array();
$userLayoutArr = array();
foreach($rowset as $row) {
	if($row->default == 1) {
		$defaultLayoutArr[] = $row;
	} else {
		$userLayoutArr[] = $row;
	}
}
?>
<div class='toolbar'>
	<div class='main'>
		<ul class='left'>
			<li>
				<select id='layout-selector' name='layout'>
					<optgroup label='默认页面'>
					<?php foreach($defaultLayoutArr as $row) {?>
						<option value='/<?php echo $row->controllerName?>.shtml' layoutId='<?php echo $row->id?>'><?php echo $row->label?></option>
					<?php }?>
					</optgroup>
					<optgroup label='自定义页面'>
					<?php foreach($userLayoutArr as $row) {?>
						<option value='/<?php echo $row->controllerName?>.shtml' layoutId='<?php echo $row->id?>'><?php echo $row->label?></option>
					<?php }?>
					</optgroup>
					<option style='background: #789; border-radius: 2px; font: italic;' value='#/admin/layout/create/'>创建新页面</option>
				</select>
			</li>
			<li><a id='enter-stage-mode' href='javascript:void(0);'>页面编辑</a></li>
			<li><a id='enter-sprite-mode' href='javascript:void(0);'>添加模块</a></li>
			<li><a id='enter-brick-mode' href='javascript:void(0);'>编辑页面模块</a></li>
			<?php
			if($this->csa->getAdminType() == 'designer') {
				if($this->csa->getSessionData('localCssMode') == 'active') {?>
			<li><a id='unload-local-css' href='javascript:void(0);' style='color: red;'>停止读取本地CSS</a></li>
			<li><a id='reload-local-css' href='javascript:void(0);' style='color: green;'>Reload CSS</a></li>
				<?php } else {?>
			<li><a id='load-local-css' href='javascript:void(0);'>读取本地CSS</a></li>
			<?php 
				}
			}
			?>
		</ul>
		<ul class='right'>
			<li><a id='enter-normal-mode' href='javascript:void(0);'>退出编辑模式</a></li>
		</ul>
	</div>
	<div class='sub'>
		<div typeId='0' class='sprite-type' draggable='true'>100%</div>
		<div typeId='1' class='sprite-type' draggable='true'>50%|50%</div>
		<div typeId='2' class='sprite-type' draggable='true'>25%|75%</div>
		<div typeId='3' class='sprite-type' draggable='true'>33%|66%</div>
		<div typeId='4' class='sprite-type' draggable='true'>66%|33%</div>
		<div typeId='5' class='sprite-type' draggable='true'>75%|25%</div>
		<div typeId='6' class='sprite-type' draggable='true'>33|33|33</div>
		<div typeId='7' class='sprite-type' draggable='true'>25|50|25</div>
		<div typeId='8' class='sprite-type' draggable='true'>25|25|25|25</div>
		<div class='clear'></div>
		
		<div style='margin: 5px;'>拖动方框至页面，为此布局添加新的STAGE。确认布局方式后点击[保存布局方案]以保存当前设置。(点击右上角[退出编辑模式]放弃所做的修改)</div>
		<a href='#/admin/layout/edit/id/<?php echo $this->layoutRow->id?>'>编辑页面属性</a>
		<div class='button' id='save-sprite-layout'>保存页面布局</div>
		<div class='button' id='enter-normal-mode'>退出页面布局</div>
	</div>
</div>