<head>
<?php
$csa = Class_Session_Admin::getInstance();
?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<?=$this->headMeta() ?>
<?=$this->headTitle() ?>

<link href="<?=Class_Server::extUrl()?>/reset.css" media="screen" rel="stylesheet" type="text/css" >
<link href="<?=Class_Server::libUrl()?>/front/style/sprite.css" media="screen" rel="stylesheet" type="text/css" >
<?php if($csa->getSessionData('localCssMode') == 'active') {?>
<link uselocal='true' href="http://local.host/<?php echo Class_Server::getSiteFolder()?>/template.css" media="screen" rel="stylesheet" type="text/css">
<?php } else {?>
<link href="<?=Class_Server::miscUrl()?>/template.css" media="screen" rel="stylesheet" type="text/css">
<?php }?>
<?=$this->headLink() ?>

<script type="text/javascript" src="<?=Class_Server::extUrl()?>/jub.js"></script>
<?=$this->headScript() ?>

<?php if($csa->isLogin()) { ?>
<link 	type="text/css" 		href="<?=Class_Server::libUrl()?>/admin/style/structure.css" media="screen" rel="stylesheet">
<link	type="text/css"			href="<?=Class_Server::libUrl()?>/admin/style/front.css" media="screen" rel="stylesheet">

<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/ajax-select-grid.js"></script>
<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/jquery.ndd.js"></script>
<script type="text/javascript"	src="<?=Class_Server::libUrl()?>/admin/script/bootstrap.js"></script>
<script type="text/javascript"	src="<?=Class_Server::libUrl()?>/admin/script/front.js"></script>
<script type="text/javascript"	src="<?=Class_Server::libUrl()?>/admin/script/drag.js"></script>
<script type="text/javascript"	src="<?=Class_Server::libUrl()?>/front/script/impact.js"></script>

<script>
/************************************/
/*Declear Global Javascript Items****/
/************************************/
var LAYOUT_STAGE_CHANGED = false;
var CURR_STATUS;
var STAGE_ID;
var SPRITE_NAME;
var MINI_BRICK_MASK;

var WB;
var FINDER;
var EventMessenger = {};
_.extend(EventMessenger, Backbone.Events);
var FILE_SERVER = "<?=Class_Server::miscUrl()?>";
</script>
<?php } ?>
</head>