<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title><?=$this->pageTitle ?></title>

<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/reset-backend.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/admin/style/structure.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/admin/style/backend.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/admin/style/tooltip.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/prompt/prompt.css" type="text/css" media="screen, projection">

<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/tab/test.css" type="text/css" media="screen, projection">

<?=$this->headLink() ?>

<script type="text/javascript" src="<?=Class_Server::extUrl()?>/jub.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/jquery.tools.min.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/jquery.ndd.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/ajax-select-grid.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/prompt/prompt.js"></script>

<script type="text/javascript" src="<?=Class_Server::extUrl()?>/tab/test.js"></script>

<script type="text/javascript" src="<?=Class_Server::libUrl()?>/script/icon-selector.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/admin/script/back.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/script/links-admin.js"></script>
<?=$this->headScript() ?>
<script>
/************************************/
/*Declear Global Javascript Items****/
/************************************/
var WB;
var FINDER;
var EventMessenger = {};
_.extend(EventMessenger, Backbone.Events);
var FILE_SERVER = "<?//=Class_HTML::server('file')?>";

window.ORG_CODE = "<?php echo Class_Server::getOrgCode()?>";
window.SITE_FOLDER = "<?php echo Class_Server::getSiteFolder()?>";
</script>
