<?=$this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?=$this->pageTitle ?></title>
<link href="/style/admin/print.css" media="all" rel="stylesheet" type="text/css" >
<style type="text/css" media="print">
	.no-printing {
		display: none;
	}
</style>
</head>

<body>
<?=$this->layout()->content ?>
</body>
</html>