<form action='' method='post' enctype='application/x-www-form-urlencoded'>
	<ul class='tab-handle'>
		<li class='handle'>基本信息</li>
		<li class='handle'>选填信息</li>
		<li class='handle'>图片和附件</li>
	</ul>
	<ul class='tab-content'>
		<?php echo $this->form;?>
		<li id='attachment' class='content-item'>
			<div class=''>
				您可以为文章添加多张图片，并选择您最满意的一张作为其缩略图
			</div>
			<div class=''>
				<div class=''>当前缩略图</div>
				<div class='introicon'>
					<img class='introicon-img' src='<?php echo Class_HTML::outputImage($this->article->introicon)?>' />
				</div>
			</div>
			<ul id='graphic-list'>
						
			</ul>
			<button callback='appendAttachmentListener' class="icon-selector" type="button" name="graphic">添加图片</button>
			<hr />
			<div class=''>
				您可以为添加附件提供下载
			</div>
			<ul id='download-list'>
						
			</ul>
			<button callback='appendAttachmentListener' class="icon-selector" type="button" name="download">添加附件下载</button>
		</li>
		<li class='handle-overlap'></li>
	</ul>
</form>
<script>
	var tmp = jQuery.parseJSON('{"obj" : <?php echo Zend_Json::encode($this->article->attachment)?>}');
	var attachmentBackboneSourceObj = tmp.obj;
	var xTime = "<?php echo $this->time?>";
	var xSig = "<?php echo $this->sig?>";
	var thumbWidth = "<?php echo $this->thumbWidth?>";
	var thumbHeight = "<?php echo $this->thumbHeight?>";
</script>
<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/attachment" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>


<script type='text/template' id='graphic-template'>
	<div class='article-image'><img src='http://misc.fucms.com/public-misc/{{ window.SITE_FOLDER }}/_thumb/{{ urlname }}'></div>
	<div class='article-name'>{{ filename }}</div>
	<div class='set-introicon' urlname='{{ urlname }}'>设置为缩略图</div>
	<input type='hidden' name='attaUrl[]' value='{{ urlname }}' />
	<input type='hidden' name='attaName[]' value='{{ filename }}' />
	<input type='hidden' name='attaType[]' value='graphic' />
</script>

<script type='text/template' id='download-template'>
	<div class='article-name'>{{ filename }}</div>
	<input type='hidden' name='attaUrl[]' value='{{ urlname }}' />
	<input type='hidden' name='attaName[]' value='{{ filename }}' />
	<input type='hidden' name='attaType[]' value='download' />
</script>