<ul class="ad-section">

</ul>

<script>
var fileUrl = "<?php echo Class_Server::fileUrl()?>";
</script>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/ad-section" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>

<script type="text/template" id="ad-section">
	<div class="images">
	<%
		for(var i = 0;i < preview.length;i++) {
	%>
		<img class="i-{{i}}" src="{{fileUrl}}/_thumb/{{preview[i]}}">
	<%
		}
	%>
	</div>
	<div class='label'>{{label}}</div>
	<div class='bb-action'>
		<a href="javascript::void(0);">编辑</a>
		<a href="/admin/ad/index/section-id/{{id}}">添加广告图</a>
	</div>
	<div style="clear:both;"></div>
</script>

<script type='text/template' id='ad-section-editor'>
	<div class='editor-title'>新建广告组</div>
	<dl>
		<dt>名字</dt>
		<dd><input class='value-field' type='text' name='label' value='' /></dd>
		<dd class='action-dd button'>SAVE</dd>
	<dl>
</script>

<script>
var createAdSection = function() {
	var template = _.template($("#ad-section-editor").html());
	adSection = new AdSection();
	var aseView = new AdSectionEditorView({
		model: adSection
	});

	
	var prompt = Prompt.getInstance().appendEditorContent(
		aseView.render().el
	).showMask();
}
</script>