<div class='create-file button'><a href='javascript:void(0)'>添加文件</a></div>
<ul class='head-files'>

</ul>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/head-file" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>

<script type='text/template' id='headfile-item-template'>
	<div class='head-file'>
		<div class='head-filename'>
			<a class='action-edit' href='javascript:void(0)'></a>
			<a href='javascript:void(0)' class='edit-all' id='{{ id }}'>{{ filename }}</a>
		</div>
		<div class='head-filetype'>{{ type }}</div>
		<div class='clear'></div>
	</div>
</script>

<script type='text/template' id='headfile-edititem-template'>
	<div class='editor-title'>新建/修改头文件</div>
	<dl>
		<dt>文件名</dt>
		<dd><input class='edit-value' type='text' name='filename' value='{{filename}}'></dd>
		<dt>文件类型</dt>
		<dd>
			<select class='edit-value' name='folder'>
				<option value='normal'>normal</option>
				<option value='helper' <%if(folder == 'helper') {%>selected<%}%>>helper</option>
			</select>
		</dd>

		<dd class='action-dd button edit-save'>SAVE</dd>
<%if(id != null){%>
		<dd class='action-dd button edit-delete'>DELETE</dd>
<%}%>
	<dl>




</script>

<script>
var createFile = function(){
	var LinkModel = new HeadFile();
	var createFile = new HeadFileEditView({
		model:LinkModel
	});
	createFile.render().el;
}
$('.create-file').click(function(){
	createFile();
});
</script>