<div class='create-file button'><a href='javascript:void(0)'>添加文件</a></div>
<ul class='head-files'>

</ul>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/head-file" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>

<script type='text/template' id='headfile-item-template'>
	<div class='head-file'>
		<div class='head-filename'>
			<a class='action-edit' href='javascript:void(0)'></a>
			<a href='javascript:void(0)' class='edit-all' id='{{ id }}'>{{ filename }}</a>
		</div>
		<div class='head-filetype'>{{ type }}</div>
		<div class='clear'></div>
	</div>
</script>

<script type='text/template' id='headfile-edititem-template'>
	<div class='editor-title'>新建/修改文件</div>
	<div class='editor-contenr'>
		<div class='filename-el'>文件名：</div>
		<div><input class='edit-value' name='filename' type='text' value='{{ filename }}'></div>
		<a class='edit-save button' href='javascript:void(0)'>保存</a>
		<a class='edit-delete button' href='javascript:void(0)'>删除</a>
	</div>
</script>

<script>
var createFile = function(){
	var LinkModel = new HeadFile();
	var createFile = new HeadFileEditView({
		model:LinkModel
	});
	createFile.render().el;
}
$('.create-file').click(function(){
	createFile();
});
</script>