<div class='section'>
	<div class='title'>网站结构</div>
	<a href='/admin/site/'>网站基本信息</a>
	<a href='/admin/group/list/type/article'>文章分组</a>
	<a href='/admin/group/list/type/product'>产品分组</a>
	<a href='/admin/group/list/type/ad'>广告分组</a>
	<a href='/admin/group/list/type/file'>文件分组</a>
</div>

<div class='section'>
	<div class='title'>管理员</div>
	<a href='/admin/admin/index'>管理员列表</a>
	<a href='/admin/acl/index'>权限分组</a>
	<!-- a href='#/admin/system/file'>查看文件</a -->
</div>

<div class='section'>
	<div class='title'>系统文件</div>
	<a href='/admin/file'>查看系统文件[包括css，js，背景图等。请勿随意删除]</a>
	<a href='/admin/system/clear-all-cache'>清除全部缓存文件</a>
</div>

<div class='clear'></div>