<div style='margin:20px 0px; width: 840px; height: 260px; border: 1px solid #ddd;'>
	<div style='line-height:20px; margin: 40px; width: 600px;'> 
    <?if(true) { ?>
        感谢您的购物,您的订单已经提交成功,您的<span style='color:red;'>订单号:<?=$this->order->id?></span>,您可以记录下来以便查询。
        <br />
    	您选定的<span style='color:red;'>配送方式为：<?if($this->d == 1) echo '快递' ;else echo '邮局';?></span>,
    	您选定的<span style='color:red;'>支付方式为：支付宝</span>,
    	您应付<span style='color:red;'>金额为￥<?=$this->order->total?></span>
    	<br />
    	<br />
    	<?if(true) { ?>
    	订单信息已发送到您的注册邮箱中,请及时查询;或可登陆“用户中心”进行查询
    	<?} else { ?>
    	您使用的是匿名帐户购买,请牢记您的帐单号,如有遗忘,您可以通过您的手机号和订单号查询您以往的订单
    	<?} ?>
    	<br />
		<a href='<?=$this->link?>' target='_paymentGatewayExt'>
			去支付页面
		</a>
    <?} else if ($this->paymentType == 3) { ?>
        感谢您的购物，您的订单已经提交成功，您的<span style='color:red;'>订单号：<?=$this->order->getData('id')?></span>，您可以记录下来以便查询。
    	您选定的<span style='color:red;'>配送方式为：<?if($this->d == 1) echo '快递' ;else echo '邮局';?></span>,
    	您选定的<span style='color:red;'>支付方式为：快钱</span>,
    	您应付<span style='color:red;'>金额为￥<?=$this->order->getData('total')?></span>
    	
    	订单信息已发送到您的注册邮箱中，请及时查询；或可登陆“用户中心”进行查询。
    	<a href='<?=$this->link?>' target='_paymentGatewayExt'><img src='/images/kuaiqian_2.jpg' /></a>
	<?} ?>
	</div>
</div>