<div class="brick-ad-group<?=$this->cssSuffix?>"  brickId='<?=$this->brickId?>'>
	<div id='fancytransition'
		data='{"width":"<?php echo $this->getParam('width')?>",
		"height":"<?php echo $this->getParam('height')?>",
		"navigation":<?php echo $this->getParam('showLinks') == 'y' ? 'true' : 'false'?>,
		"delay":<?php echo $this->getParam('delay')?>}'>
		<?php
		foreach($this->rowset as $ad) {
		?>
		<img alt="<?php echo $ad->description?>" src="<?=Class_HTML::outputImage($ad->image)?>">
		<a href='<?php echo $ad->url?>'></a>
		<?php
		}
		?>
	</div>
</div>
