<div class='container-bg'>
	<ul class='container'>
		<li class='drop-to-sort'></li>
	</ul>
</div>

<script>
saveSort = function() {
	var prompt = Prompt.getInstance().showLoadingBox();
	prompt.hideHintBox();
	
	var treeleafs = $('.treeleaf-item');
	var sortJsonStr = '{';
	treeleafs.each(function(i, leaf) {
		sortJsonStr += '"' + $(leaf).attr('id') +'":{"parentId":"'+$(leaf).attr('parent-id')+'", "sort":' + i + '},';
	});
	sortJsonStr = sortJsonStr.substring(0, sortJsonStr.length - 1);
	sortJsonStr += '}';
	
	$.ajax({
		url: '/admin/group/tree-sort/',
		data: {treeId: "<?php echo $this->doc->type?>", sortJsonStr: sortJsonStr},
		type: 'post',
		success: function(json) {
			prompt.hideLoadingBox();
		}
	});	
};

//global defines
var tree = {type: 'group', id: '<?php echo $this->doc->type?>'};
</script>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/treeleaf" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>

<script type='text/template' id='treeleaf-item-template'>
	<div class='leaf-line'>
		<div class='drag-handle' draggable='true'></div>
		<div class='leaf-label'><a href='/admin/group/edit-item/id/{{ id }}'>{{ label }}</a></div>
		<div class='leaf-link'>
		<% if(link) { %>
			{{ link }}
		<% } else { %>
			{{ id }}
		<% } %>
		</div>
		<div class='clear'></div>
	</div>
	<ul class='children'>
		<li class='drop-to-sort' parent-id='{{ id }}'></li>
	</ul>
</script>