<div class='container-bg'>
	<ul class='container'>
		<li class='drop-to-sort'></li>
	</ul>
</div>

<div id='save-sort'>SAVE SORT</div>

<script>
$('#save-sort').click(function() {
	var treeleafs = $('.treeleaf-item');
	var sortJsonStr = '{';
	treeleafs.each(function(i, leaf) {
		sortJsonStr += '"' + $(leaf).attr('id') +'":{"parentId":"'+$(leaf).attr('parent-id')+'", "sort":' + i + '},';
	});
	sortJsonStr = sortJsonStr.substring(0, sortJsonStr.length - 1);
	sortJsonStr += '}';
	
	$.ajax({
		url: '/admin/book/tree-sort/',
		data: {treeId: "<?php echo $this->doc->getId()?>", sortJsonStr: sortJsonStr},
		type: 'post',
		success: function(json) {
//			console.log('ok');
		}
	});
	
});

//global defines
var tree = {type: 'book', id: '<?php echo $this->doc->getId()?>'};
</script>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/treeleaf" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>

<script type='text/template' id='treeleaf-item-template'>
	<div class='leaf-line'>
		<div class='drag-handle' draggable='true'></div>
		<div class='leaf-label'><a href='/admin/book/edit-page/id/{{ id }}'>{{ label }}</a></div>

		<div class='quick-edit'>qe</div>

		<div class='leaf-link'>
		<% if(link) { %>
			{{ link }}
		<% } else { %>
			{{ id }}
		<% } %>
		</div>
		<div class='clear'></div>
	</div>
	<ul class='children'>
		<li class='drop-to-sort' parent-id='{{ id }}'></li>
	</ul>
</script>