<div class='group-all'>
	<div class='overlap'></div>
	<div class='group-handle'>
		<ul class='group'>
			<li class='ground'>基本信息</li>
			<li class='ground'>图片和附件</li>
		</ul>
	</div>
</div>
<div class='clear'></div>
<div class='grouplist'>
	<ul class='group-list'>
		<li><?php echo $this->form;?></li>
	</ul>
	<ul class='group-list'>
		<li>
			<fieldset class='attachment-form'>
				<ul id='attachment-list'>
					<?php 
					if(!is_null($this->attachmentArr)) {
						foreach($this->attachmentArr as $a) {
					?>
					<li filepath='<?php echo $a['filepath']?>'><?php echo $a['filename']?></li>
					<?php
						} 
					}
					?>
				</ul>
				<button callback='insertAttachment' class="icon-selector" type="button" name="">添加附件</button>
			</fieldset>
		</li>
		<li class='clear'> </li>
		<li>
			<fieldset class='product-form'>
				<ul id='product-list'>
					
				</ul>
				<button callback='insertImage' class="icon-selector" type="button" name="">添加图片</button>
			</fieldset>
		</li>
	</ul>
</div>
<div class='clear'></div>
<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/product-image" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>
<script type='text/template' id='product-add-template'>
	<div class='product-image'><img src='http://storage.aliyun.com/public-misc/{{ filepath }}'></div>
	<div class='product-name'>{{ filename }}</div>
</script>
<script type="text/javascript">
$(document).on({
	'click': function(e) {
		LI = $(e.currentTarget);
		if(confirm('移除附件:' + LI.html() + '？')) {			
			LI.remove();
		}
	}
}, '#attachment-list li');

$(document).on({
	'click': function(e) {
		LIcurrent = $(e.currentTarget);
		LI = $(e.currentTarget).find('.product-name');
		if(confirm('移除附件:' + LI.html() + '？')) {			
			LIcurrent.remove();
		}
	}
}, '#product-list li');

var saveWithAttachment = function() {
	var attachmentListLi = $('#attachment-list').find('li');
	
	var attachmentStr = '{';
	attachmentListLi.each(function(i, li) {
		attachmentStr += '"' + i +'":{"filename":"'+$(li).html()+'", "filepath":"' + $(li).attr('filepath') + '"},';
	});
	if(attachmentStr.length > 1) {
		attachmentStr = attachmentStr.substring(0, attachmentStr.length - 1);
	}
	attachmentStr += '}';
	
	var f = $("#lightbox-whitebox .content").find('form:first');
	var input = $("<input>").attr("type", "hidden").attr("name", "attachmentJson").val(
		attachmentStr
	);
	f.append(input);
	f.submit();
	
	return false;
};

</script>