<form action='' method='post' enctype='application/x-www-form-urlencoded'>
	<ul class='tab-handle'>
		<li class='handle'>基本信息</li>
		<li class='handle'>选填信息</li>
		<li class='handle'>图片和附件</li>
	</ul>
	<ul class='tab-content'>
		<?php echo $this->form;?>
		<li class='content-item'>
			<div class=''>
				您可以为产品添加多张图片，并选择您最满意的一张作为其缩略图。
			</div>
			<ul id='graphic-list'>
						
			</ul>
			<button callback='appendAttachmentListener' class="icon-selector" type="button" name="graphic">添加图片</button>
		</li>
		<li class='handle-overlap'></li>
	</ul>
</form>

<script>
	var tmp = jQuery.parseJSON('{"obj" : <?php echo Zend_Json::encode($this->product->attachment)?>}');
	var attachmentBackboneSourceObj = tmp.obj;
</script>
<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/attachment" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>


<script type='text/template' id='graphic-template'>
	<div class='product-image'><img src='http://storage.aliyun.com/public-misc/{{ window.SITE_FOLDER }}/_thumb/{{ urlname }}'></div>
	<div class='product-name'>{{ filename }}</div>
	<input type='hidden' name='attaUrl[]' value='{{ urlname }}' />
	<input type='hidden' name='attaName[]' value='{{ filename }}' />
	<input type='hidden' name='attaType[]' value='graphic' />
</script>
<!-- script type="text/javascript">
$(document).on({
	'click': function(e) {
		LI = $(e.currentTarget);
		if(confirm('移除附件:' + LI.html() + '？')) {			
			LI.remove();
		}
	}
}, '#attachment-list li');

$(document).on({
	'click': function(e) {
		LIcurrent = $(e.currentTarget);
		LI = $(e.currentTarget).find('.product-name');
		if(confirm('移除附件:' + LI.html() + '？')) {			
			LIcurrent.remove();
		}
	}
}, '#product-list li');

var saveWithAttachment = function() {
	var attachmentListLi = $('#attachment-list').find('li');
	
	var attachmentStr = '{';
	attachmentListLi.each(function(i, li) {
		attachmentStr += '"' + i +'":{"filename":"'+$(li).html()+'", "filepath":"' + $(li).attr('filepath') + '"},';
	});
	if(attachmentStr.length > 1) {
		attachmentStr = attachmentStr.substring(0, attachmentStr.length - 1);
	}
	attachmentStr += '}';
	
	var f = $("#lightbox-whitebox .content").find('form:first');
	var input = $("<input>").attr("type", "hidden").attr("name", "attachmentJson").val(
		attachmentStr
	);
	f.append(input);
	f.submit();
	
	return false;
};

</script -->