<div class='attribute-list' attributesetId ='<?php echo $this->entityId?>'>
	<div class='attribute-library'>
		<div class='attribute-library-item drag-handle' draggable='true' attribute-type='text' label='输入框'>
			输入框
		</div>
		<div class='attribute-library-item drag-handle' draggable='true' attribute-type='radio' label='单选按钮'>
			单选按钮
		</div>
		<div class='attribute-library-item drag-handle' draggable='true' attribute-type='select' label='单选下拉框'>
			单选下拉框
		</div>
		<div class='attribute-library-item drag-handle' draggable='true' attribute-type='multicheckbox' label='多选框'>
			多选框
		</div>
		<div class='attribute-library-item drag-handle' draggable='true' attribute-type='textarea' label='文本域'>
			文本域
		</div>
		<div class='attribute-library-item drag-handle' draggable='true' attribute-type='button' label='提交按钮'>
			提交按钮
		</div>
	</div>
	
	<div class='attribute-current' style='min-height: 350px;'>
	</div>
	
	<div class='attribute-editor'>
		
	</div>
	
	<div class='clear'></div>
</div>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/attributeset" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>

<script type='text/template' id='attribute-editor-template'>
	标题：<input class='attribute-field' type="text" name="label" value="{{ label }}" />
	<br />
<%
if(type == 'radio' || type == 'select' || type == 'multicheckbox') {
%>
	<div>候选项：</div>
	<ul class='option-container'>
<%
	for(idx in options) {
%>
		<li class='option-item'>
			<input class='attribute-field' type='text' name='option' value='{{ options[idx].label }}' />
			<span class='option-remove op-remove'>-</span>
		</li>
<%
	}
%>
	</ul>
	<div>
		<span class='option-add op-add'>+</span>
	</div>
<%
}
%>
	提示：<textarea class='attribute-field' name="description">{{ description }}</textarea>
	<div class='clear'></div>

	<div class='attribute-save'>SAVE</div>
</script>

<script type='text/template' id='attribute-template'>
	<div class='attribute-solid-item drag-handle' draggable='true'>
		<div class='element-label'>
			<a draggable='false' class='lightbox-trigger' attribute-id='{{ id }}' href='#'>{{ label }}</a>
		</div>
		<div class='element'>
<%
switch(type) {
	case 'text':
%>
			<input type='text' disabled='disabled'>
<%
	break;
	case 'textarea':
%>
			<textarea disabled='disabled'></textarea>
<%
	break;
	case 'radio':
		for(idx in options) {
%>
			<input type='radio' disabled='disabled' name='' value=''><label>{{ options[idx].label }}</label>
<%
		}
	break;
	case 'multicheckbox':
		for(idx in options) {
%>
			<input type='checkbox' disabled='disabled' name='' value=''><label>{{ options[idx].label }}</label>
<%
		}
	break;
	case 'select':
%>
			<select disabled='disabled' style='width:100px'></select>
<%
	for(idx in options) {
%>
			<label>{{ options[idx].label }}</label>
<%
		}
	break;
	case 'button':
%>
			<input type='submit' name='button' id='button' value='{{ label }}' /></a>
<%
	break;
}
%>
		</div>
		<div class='element-desc'>{{ description }}</div>
	</div>
</script>