<?=$this->form?>
<div class='clear'></div>

<div class='ad-list'>

</div>

<script type='text/template' id='ad-template'>
<% if(isImage == true) { %>
	<img class='clickable' src='http://st.enorange.com/public-misc/<?php echo $this->miscFolder?>/_thumb/{{ urlname }}' />
<% } else { %>
	<div class='file-type-general'></div>
<% } %>
	<br />
	<div class='info'>
		<div class='label'>{{ filename }}</div>
		<div class='upload'>上传时间:{{ uploadTime }}</div>
		<div class='size'>大小:{{ Math.ceil(size / 1024) }} KB</div>
		<div class='actions'>
			<a class='remove' href='#'>删除</a>
			<span class='open clickable'><a href='http://st.enorange.com/public-misc/<?php echo $this->miscFolder?>/{{ urlname }}' target='_blank'>打开</a></span>
		</div>
	</div>
</script>

<script data-main="<?=Class_Server::libUrl()?>/admin/script/app/ad-group" src="<?=Class_Server::libUrl()?>/admin/script/app/require-jquery.js"></script>